# Generated by Django 2.2 on 2019-07-27 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256, verbose_name='Text')),
                ('enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('required', models.BooleanField(default=True, verbose_name='Is Required')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('type', models.CharField(choices=[('R', 'Radio'), ('S', 'Dropdown'), ('C', 'Checkboxes'), ('M', 'Multi Dropdown')], default='R', max_length=1, verbose_name='Type')),
                ('other_enabled', models.BooleanField(default=False, verbose_name='Is Other Option Enabled')),
            ],
            options={
                'verbose_name': 'Multiple Choice Question',
                'verbose_name_plural': 'Multiple Choice Questions',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OptionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='Text')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Count')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('multiple_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_texts', to='multiple_choices.MultipleChoice', verbose_name='Multiple Choice')),
            ],
            options={
                'verbose_name': 'Option Text',
                'verbose_name_plural': 'Option Texts',
                'unique_together': {('multiple_choice', 'text')},
            },
        ),
        migrations.CreateModel(
            name='OptionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_uuid', models.UUIDField(editable=False, verbose_name='Customer UUID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('option_text', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='option_response', to='multiple_choices.OptionText', verbose_name='Option Response')),
            ],
            options={
                'verbose_name': 'Option Response',
                'verbose_name_plural': 'Option Responses',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='Text')),
                ('enabled', models.BooleanField(default=True, verbose_name='Is Enabled')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Order')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('multiple_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='multiple_choices.MultipleChoice', verbose_name='Multiple Choice')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'ordering': ('order',),
                'unique_together': {('multiple_choice', 'text')},
            },
        ),
    ]
