# Generated by Django 2.2 on 2019-07-07 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsurvey',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='testsurveys', related_query_name='testsurveys', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
