# Generated by Django 2.2 on 2019-04-30 06:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_uuid', models.UUIDField(editable=False, verbose_name='Survey UUID')),
                ('customer_uuid', models.UUIDField(editable=False, verbose_name='Customer UUID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('score', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
            options={
                'verbose_name': 'NPS Response',
                'verbose_name_plural': 'NPS Responses',
            },
        ),
        migrations.CreateModel(
            name='NPSSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.TextField(max_length=1000, verbose_name='Intro Text')),
                ('text_enabled', models.BooleanField(default=True, verbose_name='Is Intro Enabled')),
                ('question', models.TextField(max_length=256, verbose_name='Question')),
                ('message', models.TextField(max_length=256, verbose_name='Thank You Message')),
                ('promoters', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Promoters')),
                ('detractors', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Detractors')),
                ('passive', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Passive')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='npssurveys', related_query_name='npssurveys', to='businesses.Business', verbose_name='Business')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='npssurvey', related_query_name='npssurvey', to='surveys.Survey', verbose_name='Survey')),
            ],
            options={
                'verbose_name': 'NPS Survey',
                'verbose_name_plural': 'NPS Surveys',
            },
        ),
    ]
