# Generated by Django 2.2 on 2019-07-27 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npssurvey',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npssurveys', related_query_name='npssurveys', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='npssurvey',
            name='contra',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nps_survey', to='multiple_choices.MultipleChoice', verbose_name='Contra'),
        ),
    ]
