# Generated by Django 2.2 on 2019-07-09 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContraOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256, verbose_name='Text')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Count')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Contra Option',
                'verbose_name_plural': 'Contra Options',
            },
        ),
        migrations.AddField(
            model_name='npssurvey',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='npssurveys', related_query_name='npssurveys', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='npssurvey',
            name='contra',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nps_survey', to='multiple_choices.MultipleChoice', verbose_name='Contra'),
        ),
        migrations.CreateModel(
            name='ContraResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('contra_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contra_responses', to='nps.ContraOption', verbose_name='Contra Option')),
                ('nps_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contra_responses', to='nps.NPSResponse', verbose_name='NPS Response')),
            ],
            options={
                'verbose_name': 'Contra Response',
                'verbose_name_plural': 'Contra Responses',
            },
        ),
        migrations.AddField(
            model_name='contraoption',
            name='nps_survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contra_options', to='nps.NPSSurvey', verbose_name='NPS Survey'),
        ),
        migrations.AlterUniqueTogether(
            name='contraoption',
            unique_together={('nps_survey', 'text')},
        ),
    ]
