# Generated by Django 2.2 on 2019-04-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nps', '0001_initial'),
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npssurvey',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='npssurvey', related_query_name='npssurvey', to='surveys.Survey', verbose_name='Survey'),
        ),
    ]
