# Generated by Django 2.2 on 2019-06-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choices', '0001_initial'),
        ('nps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npssurvey',
            name='contra',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nps_survey', to='multiple_choices.MultipleChoice', verbose_name='Contra'),
        ),
    ]
